[app]
port = 2008
log_dir = 'log'
redis = 'redis://127.0.0.1/'
nats = 'localhost'
stun = 'stun:stun.l.google.com:19302'
turn = '10.19.14.155:2001'
turn_user = 'root'
turn_password = '321'
public_ip = ''
auth = false
debug = false
