[app]
port = 2008
log_dir = 'log'
redis = 'redis://127.0.0.1/'
nats = 'localhost'
stun = 'stun:stun.l.google.com:19302'
turn = 'turn:27.128.112.246:2005'
turn_user = 'root'
turn_password = '321'
# public_ip = '1.2.3.4'
auth = false
debug = false
